substitutions:
  _GCS_CACHE_BUCKET: cloudbuild-m2repo
  _SHORT_SHA: ${SHORT_SHA}
  _IMAGE_NAME: eu.gcr.io/${PROJECT_ID}/ked-pdi

steps:
  #build and push image
  - name: gcr.io/cloud-builders/docker
    id: 'build-and-push-image'
    entrypoint: bash
    args:
        - -c
        - |
          docker build -t ${_IMAGE_NAME}:${_SHORT_SHA} -f Dockerfile .
          docker push ${_IMAGE_NAME}:${_SHORT_SHA}

timeout: 9000s
tags: ['build','${_SHORT_SHA}']
